### ISSUE TITLE
Fix test-sim-import-export simulation bug

### ISSUE THREAD

**Issue by defihyung** [tendermint/liquidity#129]
## Summary of Bug

The following error occurs when running simulation `test-sim-import-export` test due to Cosmos SDK's `capability` module. [This is the exact code line](https://github.com/CosmWasm/wasmd/pull/389#issuecomment-771805302) that fails with the panic. 

Related issue: https://github.com/cosmos/cosmos-sdk/issues/8503

```
--- FAIL: TestAppImportExport (38.00s)
panic: SetIndex requires index to not be set [recovered]
        panic: SetIndex requires index to not be set
```

**Comment by kogisin** [comment]
This is an issue related to using the old database. Make sure to use `newDB` instead of `db` that is declared above.

https://github.com/tendermint/liquidity/blob/02644bba71ab243e735c9812f1557a00df65cb7b/app/sim_test.go#L153
