### ISSUE TITLE
QA Economic paper results

### ISSUE THREAD

**Issue by SenorMonito** [tendermint/liquidity#185]
QA the economic paper written here

(https://docs.google.com/document/d/1c2-LnBabTQVVn6htALlOHBI_caGLze3o7r0flqf1mek/edit)

**Comment by SenorMonito** [comment]
Notes add to Google doc

**Comment by dlguddus** [comment]
improvement of economic simulation paper is in progress, based on feedback from @SenorMonito 
expected to be finalized within this week(Mar 26)

doc link : https://docs.google.com/document/d/1c2-LnBabTQVVn6htALlOHBI_caGLze3o7r0flqf1mek/edit

**Comment by dlguddus** [comment]
doc improved based on feedback from @SenorMonito 
ready for second review.
