### ISSUE TITLE
Add generation scripts for ts/js files

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#224]
## Summary

Currently autogenerated ts, js files added to [/client/generated](https://github.com/tendermint/liquidity/tree/develop/client/generated)

And It has a dependency for [.proto](https://github.com/tendermint/liquidity/tree/develop/proto/tendermint/liquidity) files

## Proposal

so It would be better to add generating scripts to update JS/TS files according to the change of .proto files
@clockworkgr Could I get the scripts you used to generate these files?  or could you add them as a PR?

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clockworkgr** [comment]
These were generated by starport (built from develop branch at the moment).

As long as config.yml in the liquidity repo contains the key:
```
client:
  vuex:
    path: "generated"
```

If you run `starport build --rebuild-proto-once` , it will regenerate the client ts/js files.

**Comment by clockworkgr** [comment]
Once the new starport versions is released, we could try and automate this in a github action to rebuild on pushes to develop (and potentially autopublish  to npm, although this woud require TS/JS to be generated in a deterministic way so we can check whether it's changed or not...currently it isn't, see: https://github.com/tendermint/starport/issues/838)
