### ISSUE TITLE
Requested test scripts to test out the liquidity module interface

### ISSUE THREAD

**Issue by defihyung** [tendermint/liquidity#228]
## Description

From the QA, they think it would be nice to have some sample scripts to test out the liquidity module interface.

> The test scripts are used to test the liquidity module interface, and to see if the messages can be executed. These are for reference. 

## What scripts are nice to have?

The below scripts are some sample scripts that I think it is nice to have for new developers to test out the liquidity module. 
What do you think @dongsam ? If there is any specific script that you or QA team thinks it is nice to have, feel free to provide some feedback / suggestion.

### Scripts for transactions

A script to create liquidity pools
A script that requests deposits to the exist pools
A script that requests withdrawals from the exist pools
A script that requests swaps from the exist pool
A script that creates 3 different pools and makes deposits, withdrawals, and swaps from the pools

### Scripts for queries

A script to query pools
A script to query deposits
A script to query withdraws
A script to query swaps
...

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
Yes, the scripts cover every functional part sufficiently. It seems to be a good start and I think we can recombine these basic scripts in the future to add several scenarios.

**Comment by kogisin** [comment]
After having conversation with @defihyung offline, I will take over this PR.
