### ISSUE TITLE
Suggesting some features

### ISSUE THREAD

**Issue by Eiidhowz** [tendermint/liquidity#243]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

Hello,

I just want to give a suggestion.

Disclaimer: Sorry if my english is bad.

After we use trade feature, there is a square box just opened and showing our transaction result. For me it's a bit annoying, bcz If we make a deal with some pair-trade at once, maybe 3 or more transactions at once, after the transaction blocks confirmed, this kinda things always showed up and we need to click close mark (x) or (close).. 
I suggesting that would be better if the only UNSUCCESSFUL transaction showing that thing/alert (with x/close mark). But if the transaction is successful, that would be better if the result just laying on the corner right/left side or anywhere and just showed for 3-10 seconds without needed to click the close button (x/close) and slowly faded after certain durations.

Oh ya, and this one
Please add a log-out from wallet system. 
For now whenever I want to change the wallet, I have to reload the page and then change my address to another.

And last from me, would be great if there's alert when the network or wallet is wrong.
And would be great if there's a transaction records/history to every wallet and every pair. So we can track our address records/interactions with gravitydex site, if there's any events/campaign/airdrops in the future. Example, assume we in 2022, and gravitydex team want to make a events/campaign/airdrops or something that only user who complete any pair-trade with the minimum transaction of $10 at once (it means 10$ on 1 trade) before 10th May 2021(snapshoot) will be eligible for the airdrop..
And transaction records will be useful at that time (I mean for the airdrop participants),

I think that's all my opinion right now.

Thank you GravityDex team and alliance for giving us oppoturnity to join the airdrop.
Main cosmos address: cosmos1zntz99g4tet9zelh42zvycsm4kauufekhmggn7 
Testnet competition cosmos address: cosmos15g5knx73zl2ltv4qejcq39q207fypjlupc5jcx

Have a great day :)

~E

**Comment by kogisin** [comment]
Thanks for writing this up. To me, this is more like feature suggestion to [Kepler extension](https://github.com/chainapsis/kepler-extension). You might as well go to that project and post this suggestion. FYI, this repository is the core part of the Gravity DEX competition. and front-end application is solely built for the purpose of the Gravity DEX competition.

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
