### ISSUE TITLE
Received a 'math/big: cannot unmarshal ...  into a *big.Int: tx parse  error' error.

### ISSUE THREAD

**Issue by James-Osmo** [tendermint/liquidity#245]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
fixed! thank you for your report👍

**Comment by maydany** [comment]
> ## Summary of Bug
> ## Version
> ## Steps to Reproduce
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by James-Osmo** [comment]
Hey team!,

OMG this is so amazing.Thank you all. I am extremely happy to be a part of this community and supporting since the white paper days. I truly believe this is what’s going to reinvent the way we deal with assets management on every level of our society. I am a university physics student and the implications for the future excite me beyond anything else besides the expansion of our species to the actual cosmos. This is honestly revolutionary and you all should be extremely happy and proud of yourselves. I would love to be an official cosmonaut and it’s a blessing to even play a part. Thank you again.

My main hub keplr address is:

cosmos1yera5r8ancdhedeyqcumjwgpxe53au95aglgqr 

Is there anything else you’ll need?

James Dennis
***@***.***

**Comment by James-Osmo** [comment]
Hey Maydany, just following up. Just hope I don't mess anything up and not do something else thats needed.

Thanks
James
