### ISSUE TITLE
I cant trade because 0 Atom

### ISSUE THREAD

**Issue by reskyh** [tendermint/liquidity#247]
I cant completed the task because i have 0 atom
Can someone help me ?
Here my wallet address cosmos1ek238pj99nmdtnaeqt2hakhh2q8cqul0tz6dvg

**Comment by maydany** [comment]
Since we didn't enable the send, no one can send coin😂

**Comment by gsq2477** [comment]
> Since we didn't enable the send, no one can send coin😂

So, who can help us?
Or we can't continue the test?

**Comment by dongsam** [comment]
I don't think there's a way at this point in policy. I'm sorry. If it's possible, I'll leave a comment. 😂
