### ISSUE TITLE
Combining the swap and price pages, or adding a swap feature in the price page.

### ISSUE THREAD

**Issue by James-Osmo** [tendermint/liquidity#250]
## Summary

<"I am usually trying to squeeze as much time as possible into testing the user perspective but doing so subjects me to little mistakes like trying to perform a swap on the fly. When I notice a great buying opportunity and click the pair, during the page redirect the price changes and is almost never in the vicinity of where I would pull the trigger; I'm a big percentage person. This is where the title says it all.>

## Problem Definition

 Less traffic to the swap page. Leaving it redundant.

## Proposal

<"To create a side swap-box built into the price page to increase efficiency of swaps and allow for full advantage of price fluctuations.>

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
This repository is the core part of the Gravity DEX incentivized testnet and this feature request is for the front-end application. As the competition towards the end, we are going to have to close this issue.
