### ISSUE TITLE
Every time I open the ranking tab I have to refresh page for it to display information.

### ISSUE THREAD

**Issue by James-Osmo** [tendermint/liquidity#251]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hallazzang** [comment]
Sorry for the inconvenience. We found that people who connect to the API server in US zone may face this issue.
There's very heavy load on our server right now and we are considering to upgrade the server's spec.

**Comment by James-Osmo** [comment]
No need to apologize, honest. This is the whole point of the test net. I am loving it so far. I am in Canada PST time and I am still at it trying to figure out ways to improve it but so far I am liking it. There is one thing thats been happening a lot; when I try to take advantage of a price distortion, as soon as I click the swap button and go to pay the gas fee, the price dramatically drops. Then I cancel it, it goes back to the previously distorted price. I lost so many tokens from this. I went from being in the top 1000 to the top 10000 due to this happening. Its awful lol 

James Dennis
***@***.***
