### ISSUE TITLE
Swapping bug.

### ISSUE THREAD

**Issue by Southpreme** [tendermint/liquidity#252]
Hello, in the attached video i tried to swap LUNA to DSM.
At first, i swapped from LUNA to DSM, my balance changed from 33.017 to 33.850. Right after, when i swapped back from DSM to LUNA, my balanced changed from 33.843 to 32.129.
The impact of my blances was even bigger when i tried to swap with bigger volume.

**Comment by kogisin** [comment]
As the Gravity DEX competition towards the end. We will have to close this issue.
