### ISSUE TITLE
Clicking on token pair to swap in price tab results in broken links on swap page

### ISSUE THREAD

**Issue by simplemath03** [tendermint/liquidity#256]
Hi,

I noticed that when browsing the price tab and selecting a token pair I would like to trade (left-clicking the token pair on the price tab), it will often take me to the swap page with broken icons for the token pair. This doesn't happen 100% of the time but does happen more than 60% of the time. Please reply if you have additional questions or want more information.

P.S. I am using the Brave web browser.

**Comment by simplemath03** [comment]
![Screenshot from 2021-05-06 14-51-55](https://user-images.githubusercontent.com/51931228/117357672-d8b64880-ae7a-11eb-8cde-433197eda5e9.jpg)

See attached for a screenshot of the issue

**Comment by maydany** [comment]
> Hi,
> 
> I noticed that when browsing the price tab and selecting a token pair I would like to trade (left-clicking the token pair on the price tab), it will often take me to the swap page with broken icons for the token pair. This doesn't happen 100% of the time but does happen more than 60% of the time. Please reply if you have additional questions or want more information.
> 
> P.S. I am using the Brave web browser.

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by simplemath03** [comment]
Thank you so much for the great experience! Had a wonderful time competing, looking forward to using Gravity DEX when it goes live!

My Cosmos Address is as follows:
cosmos1fjtzmf94mntv3fp7d45vst3yvmaqdmgekz070d
