### ISSUE TITLE
i couldnt receive competition test money?

### ISSUE THREAD

**Issue by Lmwatt** [tendermint/liquidity#257]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
If you leave your email and wallet address, I will check it.

**Comment by Tosinawe** [comment]
I did not receive the gravity dex competition tokenso I cannot participate in the competition. please help. my email address is: jidexonline@yahoo.com and my wallet address is: cosmos1pftpwa2uvt9s3t5452m2he9cppuc5luc098urn

**Comment by dongsam** [comment]
Hi, @Tosinawe Hi `cosmos1pftpwa2uvt9s3t5452m2he9cppuc5luc098urn` is the mainnet address you submitted and the competition address is `cosmos1uwayvvfp826afqy0w3uga2q9qxnf6dxjn9vjqa`. Would you check your wallet `cosmos1uwayvvfp826afqy0w3uga2q9qxnf6dxjn9vjqa`?

**Comment by Lmwatt** [comment]
> Hi @Lmwatt If you leave your email and wallet address, I will check it.

my wallet address: cosmos1sz45hmvramaxvnl7e2w6zsr340zy6qpqrrfk5e

my e mail: eesula@gmail.com

Regards,

**Comment by Tosinawe** [comment]
![image](https://user-images.githubusercontent.com/83822018/117536809-8d787300-affd-11eb-8054-f7bee94884b2.png)

while checking my rank I show up as inelligibe -can you help out please?

email is jidexonline@yahoo.com
![Uploading pool ranking.PNG…]()

**Comment by dongsam** [comment]
> my wallet address: cosmos1sz45hmvramaxvnl7e2w6zsr340zy6qpqrrfk5e
> 
> my e mail: [eesula@gmail.com](mailto:eesula@gmail.com)

Unfortunately, the email and address do not exist on the competition registration submission list. Did you normally register for the competition? @Lmwatt

**Comment by dongsam** [comment]
> while checking my rank I show up as inelligibe -can you help out please?
> 

only top 1/3rd are eligible for prizes, and that means you are not in top 1/3rd @Tosinawe
