### ISSUE TITLE
Wallet keeps disconnecting from the dex every now and then. At least 1 in 10 page changes.

### ISSUE THREAD

**Issue by James-Osmo** [tendermint/liquidity#259]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
As the Gravity DEX competition has ended, we are closing this issue unless it is related to either a bug or feature request to the liquidity module.
