### ISSUE TITLE
daily missions always zero showing

### ISSUE THREAD

**Issue by weatherside** [tendermint/liquidity#260]
## Summary of Bug

swap and pool daily mission keep showing zero even i made swaps and add lp

## Steps to Reproduce

swaps some coins/tokens
add some liquidity to pools
daily missions never changing
show 0/3 swaps
show 0/3 liquidty pools

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lann92** [comment]
I have the same issue today.

**Comment by lann92** [comment]
looks like it is working now

**Comment by weatherside** [comment]
it backs to normal again, closed.
