### ISSUE TITLE
Is it possible to have the slippage locked after changing it? That would be so awesome and save so much time.

### ISSUE THREAD

**Issue by James-Osmo** [tendermint/liquidity#262]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
duplicated issue https://github.com/tendermint/liquidity/issues/261
