### ISSUE TITLE
Changing swap order reduces base transaction value.

### ISSUE THREAD

**Issue by cordnel** [tendermint/liquidity#264]
## Summary

Changing the order of swap (such as from atom->dvpn to dvpn-> atom) reduces the entered value slightly every time the arrow icon is clicked. 

## Brief Description 

If we consider this screenshot, we are swapping 1 atom to dvpn. When the order is switched (dvpn to atom), 1 atom reduces to 0.99112 atom, as visible in figure 2. It further reduces if you keep clicking on the arrow icon to switch swap order, but this time with dvpn. It isn't a major issue, but marginal change between the original transaction and slightly reduced value can affect the UX for non-savvy users. 

This issue appears to be caused because the value of primary token updates with reference to the value of the secondary token every time the swap order is changed, instead of the original value entered by the user. 

Figure 1

![1](https://user-images.githubusercontent.com/83818415/117443673-1dfb7880-af56-11eb-9078-74fc837582dd.PNG)

Figure 2

![2](https://user-images.githubusercontent.com/83818415/117444133-abd76380-af56-11eb-8f90-3d713c410dd2.PNG)

Figure 3

![3](https://user-images.githubusercontent.com/83818415/117444145-af6aea80-af56-11eb-8f11-deb50b9eafaa.PNG)

## Version

Unable to find version on the website https://gravity.bharvest.io

## Steps to Reproduce

Choose any trading pair and enter a value for the first token. A corresponding swap value will appear in the second token's textview. 
Click on the arrow icon between the two tokens and change swap direction. Each time direction is changed, the base values reduce slightly. 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
> ## Summary
> Changing the order of swap (such as from atom->dvpn to dvpn-> atom) reduces the entered value slightly every time the arrow icon is clicked.
> 
> ## Brief Description
> If we consider this screenshot, we are swapping 1 atom to dvpn. When the order is switched (dvpn to atom), 1 atom reduces to 0.99112 atom, as visible in figure 2. It further reduces if you keep clicking on the arrow icon to switch swap order, but this time with dvpn. It isn't a major issue, but marginal change between the original transaction and slightly reduced value can affect the UX for non-savvy users.
> 
> This issue appears to be caused because the value of primary token updates with reference to the value of the secondary token every time the swap order is changed, instead of the original value entered by the user.
> 
> Figure 1
> 
> ![1](https://user-images.githubusercontent.com/83818415/117443673-1dfb7880-af56-11eb-9078-74fc837582dd.PNG)
> 
> Figure 2
> 
> ![2](https://user-images.githubusercontent.com/83818415/117444133-abd76380-af56-11eb-8f90-3d713c410dd2.PNG)
> 
> Figure 3
> 
> ![3](https://user-images.githubusercontent.com/83818415/117444145-af6aea80-af56-11eb-8f11-deb50b9eafaa.PNG)
> 
> ## Version
> Unable to find version on the website https://gravity.bharvest.io
> 
> ## Steps to Reproduce
> Choose any trading pair and enter a value for the first token. A corresponding swap value will appear in the second token's textview.
> Click on the arrow icon between the two tokens and change swap direction. Each time direction is changed, the base values reduce slightly.
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Thank you for the report👍 When it comes to mainnet, it will be fixed

**Comment by cordnel** [comment]
Thank you.
cosmos166w07kte0je0ydkvclapfxvra6w25aj0vnhwu5
