### ISSUE TITLE
2 bugs i reported on discord/telegram.

### ISSUE THREAD

**Issue by chadcapitalist** [tendermint/liquidity#265]
I didn't know we were supposed to post bug reports here, i just posted them on discord and telegram. The issues are now fixed but i was the first to report these issues. so im posting this here, in case posting on discord/telegram doesn't make me eligible for bug bounty. For report #1 someone from b-harvest even sent me a DM saying "Thank you for bug reporting. We will back to you after analysis" Let me know if i need to post proof that i was the first to report these bugs.

## Summary of Bug

Report #1 - https://mega.nz/file/t9ciVbpa#2c4JKcl4VIdAvSpTrr4A0Zu5Mw8_lM6n47Hx5NalxtM
The transaction wouldn't go through unless I skimmed off numbers after the decimal.

Report #2 - https://mega.nz/file/t5VknJSJ#m7HK2-GZG3DUN8SFW5kuK17lJoyq-_7aKnjoY80LNkw
Tokens wouldn't get added to the pool unless i skimmed off the numbers after the decimal.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
As you mentioned these were fixed during the competition. And definitely it is not a bug related to liquidity module itself : )

**Comment by maydany** [comment]
> I didn't know we were supposed to post bug reports here, i just posted them on discord and telegram. The issues are now fixed but i was the first to report these issues. so im posting this here, in case posting on discord/telegram doesn't make me eligible for bug bounty. For report #1 someone from b-harvest even sent me a DM saying "Thank you for bug reporting. We will back to you after analysis" Let me know if i need to post proof that i was the first to report these bugs.
> 
> ## Summary of Bug
> Report #1 - https://mega.nz/file/t9ciVbpa#2c4JKcl4VIdAvSpTrr4A0Zu5Mw8_lM6n47Hx5NalxtM
> The transaction wouldn't go through unless I skimmed off numbers after the decimal.
> 
> Report #2 - https://mega.nz/file/t5VknJSJ#m7HK2-GZG3DUN8SFW5kuK17lJoyq-_7aKnjoY80LNkw
> Tokens wouldn't get added to the pool unless i skimmed off the numbers after the decimal.
> 
> ## Version
> ## Steps to Reproduce
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by chadcapitalist** [comment]
> > I didn't know we were supposed to post bug reports here, i just posted them on discord and telegram. The issues are now fixed but i was the first to report these issues. so im posting this here, in case posting on discord/telegram doesn't make me eligible for bug bounty. For report #1 someone from b-harvest even sent me a DM saying "Thank you for bug reporting. We will back to you after analysis" Let me know if i need to post proof that i was the first to report these bugs.
> > ## Summary of Bug
> > Report #1 - https://mega.nz/file/t9ciVbpa#2c4JKcl4VIdAvSpTrr4A0Zu5Mw8_lM6n47Hx5NalxtM
> > The transaction wouldn't go through unless I skimmed off numbers after the decimal.
> > Report #2 - https://mega.nz/file/t5VknJSJ#m7HK2-GZG3DUN8SFW5kuK17lJoyq-_7aKnjoY80LNkw
> > Tokens wouldn't get added to the pool unless i skimmed off the numbers after the decimal.
> > ## Version
> > ## Steps to Reproduce
> > ## For Admin Use
> > 
> > * [ ]   Not duplicate issue
> > * [ ]   Appropriate labels applied
> > * [ ]   Appropriate contributors tagged
> > * [ ]   Contributor assigned/self-assigned
> 
> Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

thanks a lot!
here is my mainnet address - cosmos14d4mek8tj5uef7gxpg6lp3ur6f5j3ka8esw9wc

**Comment by chadcapitalist** [comment]
thanks a lot!
here is my mainnet address - cosmos14d4mek8tj5uef7gxpg6lp3ur6f5j3ka8esw9wc
