### ISSUE TITLE
Attempted to add liquidity, but instead it swapped

### ISSUE THREAD

**Issue by c0deNoodle** [tendermint/liquidity#266]
## Summary of Bug

I had previously had issues using a Ledger to connect to the GravityDex (but this isn't about that).  However, because many transactions I attempted ended up failing, it seems one was 'left in the queue' so to speak.  The first successful transaction I attempted was to add liquidity to the BTSG-COM pool.  When I saw success pop up on the screen, I noticed that it did not add liquidity to that pool, but instead executed a swap from ATOM to AKT.  I have attached a screenshot of the screen, and you can see the liquidity menu behind the swap confirmation.
![bug](https://user-images.githubusercontent.com/83823979/117457227-03ee7580-af17-11eb-8696-3ee2f4da1ca9.PNG)

## Steps to Reproduce

Failed transactions (may only using Ledger) can take the place of the very next successful transaction.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your reporting. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
