### ISSUE TITLE
Colorblind Accessibility Issue - Transaction Results Screen

### ISSUE THREAD

**Issue by c0deNoodle** [tendermint/liquidity#268]
## Summary

The red colored text on the transaction confirmation screen that comes up can be very hard to see on such a colorful background.  Take someone with colorblindness and this gets even more difficult.
![colorblind-2](https://user-images.githubusercontent.com/83823979/117459192-21bcda00-af19-11eb-910e-f45126de2786.png)

## Problem Definition

The main problem this would address: those with colorblindness of different varieties would have harder time accessing and using the GravityDex without these minor changes.

## Proposal

The red colored text could be changed to a lighter orange version.  Alternatively, some kind of background bubble with a light background can be placed behind the number areas to make them more legible in their current font color.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
