### ISSUE TITLE
Insufficient balance bug

### ISSUE THREAD

**Issue by namnh2204** [tendermint/liquidity#269]
## Summary of Bug

Insufficient balance although I got some COM to swap.

## Version

v1.2.5

## Steps to Reproduce

Suppose that you have a couple of COM and 0 GCYB. You choose to swap GCYB for COM. Enter the random number of GCYB. The Insufficient button appear. Now you click the arrow button to change to swap COM for GCYB. The Insufficient button still there.
![image](https://user-images.githubusercontent.com/29002417/117464803-3762eb80-af7b-11eb-9b9e-9f75b77ed88f.png)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
> ## Summary of Bug
> Insufficient balance although I got some COM to swap.
> 
> ## Version
> v1.2.5
> 
> ## Steps to Reproduce
> Suppose that you have a couple of COM and 0 GCYB. You choose to swap GCYB for COM. Enter the random number of GCYB. The Insufficient button appear. Now you click the arrow button to change to swap COM for GCYB. The Insufficient button still there.
> ![image](https://user-images.githubusercontent.com/29002417/117464803-3762eb80-af7b-11eb-9b9e-9f75b77ed88f.png)
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by namnh2204** [comment]
> > ## Summary of Bug
> > Insufficient balance although I got some COM to swap.
> > ## Version
> > v1.2.5
> > ## Steps to Reproduce
> > Suppose that you have a couple of COM and 0 GCYB. You choose to swap GCYB for COM. Enter the random number of GCYB. The Insufficient button appear. Now you click the arrow button to change to swap COM for GCYB. The Insufficient button still there.
> > ![image](https://user-images.githubusercontent.com/29002417/117464803-3762eb80-af7b-11eb-9b9e-9f75b77ed88f.png)
> > ## For Admin Use
> > 
> > * [ ]   Not duplicate issue
> > * [ ]   Appropriate labels applied
> > * [ ]   Appropriate contributors tagged
> > * [ ]   Contributor assigned/self-assigned
> 
> Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

Thank you. My Cosmos Hub mainnet address: cosmos1x37svrswz5xg688845fy5ugwspawp3eczdjl2e
