### ISSUE TITLE
Swapping into or out of ATOM gas fee issue

### ISSUE THREAD

**Issue by SpongeBobCashPants** [tendermint/liquidity#271]
## Summary of Bug

The Dex does not allow you to pay the gas fee with proceeds. If you are conducting a transaction with ATOM involved on either end it should be able to just take the gas from the buy or sell transaction. Otherwise, how would someone with no atom swap for atom etc.. I'm thinking this is an error because it doesn't make any sense. I got stuck without enough atom and no way to swap for some.

## Version

The current 5/7 beta competition version

## Steps to Reproduce

Try to swap into atom with no atom (or not enough) in your account

Cheers, Ray
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
