### ISSUE TITLE
Transaction Broadcast "FAIL" bug after closing dialog without executing swap.

### ISSUE THREAD

**Issue by cordnel** [tendermint/liquidity#273]
## Summary of Bug

After initiating a swap, the keplr wallet pops up, but then you realise the slippage is too high, or there is some other issue. So you close the "swap steps" dialog box in the top right corner. After  changing the slippage, and reinitating the swap, it opens up the dialog box of the previous transaction which displays "failed". This dialog box does not go away until you execute the new swap outside the gravity dex interface, in keplr. It keeps showing failed, even if you acknowledge that it has failed by clicking close.

## Version

Website doesn't display version.

## Steps to Reproduce

First open up the swap page on gravity dex. Any pair will do.

![1](https://user-images.githubusercontent.com/83818415/117502650-7013bc80-af9d-11eb-99cf-a8c5d1ffe6e6.PNG)

Here user decides to cancel the transaction to change slippage or for some other reason. 
![2](https://user-images.githubusercontent.com/83818415/117503145-2d9eaf80-af9e-11eb-9cba-8af995c976cf.PNG)

After changing the slippage and reinitating the transaction, the "failed" message appears in the swap steps dialog box.
![3](https://user-images.githubusercontent.com/83818415/117503291-5de64e00-af9e-11eb-9980-a3d8f37b6667.PNG)

If you close the dialog box and try again, the same message appears. Then you must simply accept the transaction on keplr to get the "failed" dialog to go away.
![image](https://user-images.githubusercontent.com/83818415/117503463-9dad3580-af9e-11eb-9e47-89f63b92705c.png)

After this, the normal dialog box displaying the actual success or failure of the newest transaction appears.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Really Thank you for the detailed report!! 👍
Sorry for the inconvenience during the test
In later, we will investigate the relation of keplr and web : )
