### ISSUE TITLE
Failed transaction burned all of Atom

### ISSUE THREAD

**Issue by BusinezBear** [tendermint/liquidity#274]
## Summary of Bug

I noticed I only had 0.4 ATOM left. I tried to swap REGEN to ATOM. Transaction failed, but still burnt 0.3 ATOM. Not enough ATOM left to continue participating.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
tx fee is always charged😢
