### ISSUE TITLE
add or fix feature: dominant token icon first and weak token icon second

### ISSUE THREAD

**Issue by flarnrules** [tendermint/liquidity#276]
## Summary
On the price page, the dominant token icon should display first. Perhaps this feature has already been implemented, in which I would like to report this as a bug.

## Problem Definition
This feature will allow traders to more readily assess which trades will yield arbitrage opportunities.
Confusion about the order of the token icon.
Improved user experience.
Not to my knowledge. Difficulty in implementation perhaps?

## Proposal
On the price page, the dominant token always should display first, then the weaker token

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
