### ISSUE TITLE
Too many tokens break the Price | X token for Y token | Swap

### ISSUE THREAD

**Issue by simondelarue14** [tendermint/liquidity#277]
## Summary of Bug

![image](https://user-images.githubusercontent.com/51883276/117517881-cd0f7280-af9d-11eb-8e3a-8b7717937e11.png)
As you can see on the screenshot the number of Regen for LUNA is broken, it should say zero but instead all the zeros are removed because there is too much
![image](https://user-images.githubusercontent.com/51883276/117517972-460eca00-af9e-11eb-9ecf-f047169b6e4c.png)

it happens with every tokens
![image](https://user-images.githubusercontent.com/51883276/117517912-f4663f80-af9d-11eb-9ad1-f0ce9a80141d.png)
I know it's not really useful but it should be fixed

## Version

Release v1.2.5

## Steps to Reproduce

Just input a lot of tokens in the swap and you should encounter the same bug

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
> ## Summary of Bug
> ![image](https://user-images.githubusercontent.com/51883276/117517881-cd0f7280-af9d-11eb-8e3a-8b7717937e11.png)
> As you can see on the screenshot the number of Regen for LUNA is broken, it should say zero but instead all the zeros are removed because there is too much
> ![image](https://user-images.githubusercontent.com/51883276/117517972-460eca00-af9e-11eb-9ecf-f047169b6e4c.png)
> 
> it happens with every tokens
> ![image](https://user-images.githubusercontent.com/51883276/117517912-f4663f80-af9d-11eb-9ad1-f0ce9a80141d.png)
> I know it's not really useful but it should be fixed
> 
> ## Version
> Release v1.2.5
> 
> ## Steps to Reproduce
> Just input a lot of tokens in the swap and you should encounter the same bug
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.
