### ISSUE TITLE
Wallet not refreshing at the same time

### ISSUE THREAD

**Issue by simondelarue14** [tendermint/liquidity#279]
## Summary of Bug

Between 2 pages, my money wasn't the same amount, they should refresh at the same time so that it isn't confusing
![image](https://user-images.githubusercontent.com/51883276/117518922-eca89a00-afa1-11eb-8dcf-345afb3bb685.png)
![image](https://user-images.githubusercontent.com/51883276/117518928-f205e480-afa1-11eb-8978-6ab43f925ff1.png)

## Version

v1.2.5

## Steps to Reproduce

Open 2 different tabs and you can reproduce it

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your reporting. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us. 

Thank you! 😊
