### ISSUE TITLE
Clicking on Pairs

### ISSUE THREAD

**Issue by LAJazzDrum** [tendermint/liquidity#282]
I am using a Lenovo i7 ThinkPad. When I want to trade I have to go to the swap screen, and clicking on a pair in the price of screen does not work right. If I am looking at the prices screen and click on a trading pair it sends me to the swap screen, but with broken picture links and it will not let me complete the transaction.

Contestant: Caterpillar1
cosmos14f729zcv5.....ggnz6l03u

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
