### ISSUE TITLE
Hyperlinks to CoinMarketCap or Coin's Site

### ISSUE THREAD

**Issue by LAJazzDrum** [tendermint/liquidity#284]
It would be nice if it was easier to do research on the new coins. Perhaps a link to each one's website, or to the coin's page on CoinMarketCap and/or CoinGecko? Maybe some kind of internal site similar to Wikipedia where everyone using the dex can help describe it, add citations, plus edit & argue.

Contestant: Caterpillar1
cosmos14f729zcv5.....ggnz6l03u

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
