### ISSUE TITLE
Total Swap Fee Estimator/Calculator

### ISSUE THREAD

**Issue by LAJazzDrum** [tendermint/liquidity#285]
I am still confused why doing an arbitrage trade that is supposed to be 2.5% does not seem to net me anything. It would be nice if there was some sort of fee calculator that helped me add the gas, trade fees, etc so I know exactly how much of my trade money is being burned.

Contestant: Caterpillar1
cosmos14f729zcv5.....ggnz6l03u

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
