### ISSUE TITLE
Adding low amount of liquidity in pool gives wrong pool share value

### ISSUE THREAD

**Issue by Nono327** [tendermint/liquidity#288]
## Summary of Bug

Adding low amount of liquidity in pool gives wrong pool share value
## Version
Release for gravity dex competition

## Steps to Reproduce
Add 1 cent of liquidity in a pool
Expected : you get a very low amount of pool share.
Given : you get a few percents.

Example : I added 1 cent in the atom/iris pool, I got 2.278% pool share, but revenue from fees seems unaffected

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
I think it was a test page decimal error! thank you for reporting : ) since competition event is over, I think I should close this one. I hope I had a time to fix this!

**Comment by maydany** [comment]
> ## Summary of Bug
> Adding low amount of liquidity in pool gives wrong pool share value
> 
> ## Version
> Release for gravity dex competition
> 
> ## Steps to Reproduce
> Add 1 cent of liquidity in a pool
> Expected : you get a very low amount of pool share.
> Given : you get a few percents.
> 
> Example : I added 1 cent in the atom/iris pool, I got 2.278% pool share, but revenue from fees seems unaffected
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by Tonzofdamage** [comment]
Hello,

Thank you for the competition !
This is the address that I'll use to receive the competition prize
: cosmos1mnqngvfwt5k276j5v85kpscqpegjafpcvvcnlz
My github name is Tonzofdamage and its corresponding ID is 9832035.

Please contact me if I missed anything, and thanks again !


Le mer. 19 mai 2021 à 11:22, Lim Sung-hoon ***@***.***> a
écrit :
