### ISSUE TITLE
Pool Pair Icon Buy or Sell Tab

### ISSUE THREAD

**Issue by LAJazzDrum** [tendermint/liquidity#290]
It would be nice on the price screen if you could not only select coins, but also select one coin and whether you wanted it to be in the buy or sell side of the trade. For example, if I click on Iris and sell it will prioritize arbitrage opportunities that involve selling Iris.

Contestant: Caterpillar1
cosmos14f729zcv5.....ggnz6l03u

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
