### ISSUE TITLE
Max Icon Disappear when Swap coin

### ISSUE THREAD

**Issue by BaoHo2612** [tendermint/liquidity#291]
## Proposal

Hi admin, When I swap the coin that input coin is larger than the balance coin, Swap button disappear as the video, I caused some inconvenient when I do transactions
![Swap button]
(https://user-images.githubusercontent.com/78771811/117532900-01257a80-b014-11eb-9ba2-82bad3d81348.PNG)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
In fact, because you input the more coin than you have : )
Thank you for participating our test!! 🚀
