### ISSUE TITLE
Can not redeem 99% of the AKT/DVPN pool

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#293]
## Summary of Bug

When trying to redeem 99 % of the pool I am getting this error
![image](https://user-images.githubusercontent.com/83839143/117537087-1b089280-afff-11eb-84da-8312ca3d9e8c.png)

## Version

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm

## Steps to Reproduce

I had some amount of tokens in AKT/DVPN pool (approx 2000 USD, maybe slightly more). When trying to redeem 99 % multiple times in a row I got this error. Then I tried to redeem 100 % and it worked. 

What is wrong?

The same thing happened to me yesterday:

![image](https://user-images.githubusercontent.com/83839143/117537141-6a4ec300-afff-11eb-92ad-0fd22a3039ae.png)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
I think it might be a front end input decimal error thank you for reporting!👍

**Comment by maydany** [comment]
> ## Summary of Bug
> When trying to redeem 99 % of the pool I am getting this error
> ![image](https://user-images.githubusercontent.com/83839143/117537087-1b089280-afff-11eb-84da-8312ca3d9e8c.png)
> 
> ## Version
> I don't know how to find out the version but my contest wallet address is following:
> cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm
> 
> ## Steps to Reproduce
> I had some amount of tokens in AKT/DVPN pool (approx 2000 USD, maybe slightly more). When trying to redeem 99 % multiple times in a row I got this error. Then I tried to redeem 100 % and it worked.
> 
> What is wrong?
> 
> The same thing happened to me yesterday:
> 
> ![image](https://user-images.githubusercontent.com/83839143/117537141-6a4ec300-afff-11eb-92ad-0fd22a3039ae.png)
> 
> ## For Admin Use
> * [ ]  Not duplicate issue
> * [ ]  Appropriate labels applied
> * [ ]  Appropriate contributors tagged
> * [ ]  Contributor assigned/self-assigned

Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

**Comment by Kopyno** [comment]
> Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

Hello, 
thank you very much for such a good news. I appreciate it. 

My Cosmostation ATOM wallet (which I registered for the price distribution) is following:
cosmos1l5prt6y8vkqegxfhlqf89apcpd56m43zrpvs5q

In case of any queries I am available 
With Best Regards
Kopyno
