### ISSUE TITLE
Pool price clicking on Price evaluation Rule when delay alert is here opens delay alert infos

### ISSUE THREAD

**Issue by simondelarue14** [tendermint/liquidity#297]
## Summary of Bug

![image](https://user-images.githubusercontent.com/51883276/117547492-2922d700-b030-11eb-9056-578690703c04.png)

When the Delayed Price Date alert is here, clicking on the Coin Price Evaluation Rule button shows the Delayed Price Data menu instead of his own menu

## Version

v1.2.5

## Steps to Reproduce

Click on the Coin Price Evaluation Rule button to show the Delayed Price Data menu

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Good finding! sorry for the inconvenience : ) I was busing to solve other thing. I hope I had a time to fix this... thank you for reporting!!
