### ISSUE TITLE
USD equivalent feature for SWAP option

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#299]
## Summary

Adding USD equivalent or at least info to SWAP dialog window. 

## Problem Definition

Sometimes I want to swap certain amount of USD to specific coin. In current situation I have to calculate the needed amount manually and after initial swap I have to swap more or sell until I get the amount wanted.

## Proposal

1) Add a USD equivalent next to the coin symbol for information

or maybe even better

2) add a USD equivalent next to the coin symbol with possibility to insert **inlet or output equivalent amount of USD** wanted, which would drive the amount and ratio for both tokens for the swap.

example:
I want to convert 100 USD equivalent of ATOM to AKT. At the moment I have to calculate that I have 23,6 ATOM worth of 661,17 USD. Therefore 1 ATOM is worth 28,015 USD. To send amount of 100 USD I need to swap (100/28,01) 3,569 ATOM to AKT.
If there was a feature or possibility right next to inserting the amount of tokens where I would insert the amount of USD equivalent I want to transfer or receive via two selected coins and the ratio was set accordingly, it might be in my opinion very helpful.

![image](https://user-images.githubusercontent.com/83839143/117551694-a1e15d80-b047-11eb-93af-0f8fc12e7344.png)

![image](https://user-images.githubusercontent.com/83839143/117551927-defa1f80-b048-11eb-9e2e-449a4dc06a98.png)

This might also help users to swap the minimum amount of USD in tokens less then two decimals of token which they are not able to swap back at the moment. 

![image](https://user-images.githubusercontent.com/83839143/117552015-3d270280-b049-11eb-8b44-440d0f24697a.png)

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of test again, we will do our best to reflect the feedback you gave us. 

Thank you! 😊
