### ISSUE TITLE
Some bugs that I found

### ISSUE THREAD

**Issue by sonntuet1997** [tendermint/liquidity#300]
## Summary of Bug
Please check for me if some of them are duplicated as there are just some bugs that I quickly noted while using the app.
Any more minor bugs I will comment in this post!

Sometimes, the UI reported that the transaction I made failed, but it's actually success after that 
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sonntuet1997** [comment]
I can set gas limit to 100000 from 300000 by modifying code on the UI

**Comment by sonntuet1997** [comment]
![image](https://user-images.githubusercontent.com/33181397/117585205-61630c00-b13b-11eb-8b60-5a94980305ef.png)
the msg_height 's type should be uint64 as its value cannot be a negative number (apply for all msg_height property in the above file

**Comment by sonntuet1997** [comment]
Almost every time when you click into the "Coin Price Evaluation Rule", nothing happen!

**Comment by dongsam** [comment]
> the msg_height 's type should be uint64 as its value cannot be a negative number (apply for all msg_height property in the above file

Tendermint and Cosmos-SDK are using Height as int64 type, so we implemented the same.
You can check that [here](https://github.com/tendermint/tendermint/blob/70bb8cc8b70dcb357e069ebe60b26a85c7994760/types/block.go#L337)
