### ISSUE TITLE
USD equivalent for add liquidity feature

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#301]
## Summary

Adding calculator for determining needed amount of X and Y token for given USD value user wants to add to the pool

## Problem Definition

If I decide to divide my overall liquidity equally between for example all AKT/XY pools, I might need to distribute (for example) 2000 USD worth of coins to every AKT pool. However it is quite difficult to determine the needed amount of X and Y coin needed for this operation. 
## Proposal

Add a USD equivalent feature, where:

1) user will see equivalent of USD added to the pool for selected amount of X and Y coins by him

or, maybe, even better:

2) user will set a certain amount of USD he wants to add to the pool and it will immediately show the needed amount of X and Y token based on current ratio of the pool. 

With above mentioned features user know how many X and Y tokens he needs to swap for adding 2000 USD worth of liquidity to the selected pool.

![image](https://user-images.githubusercontent.com/83839143/117554021-4fa73900-b055-11eb-82fe-4c16e71b5d4d.png)

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
