### ISSUE TITLE
Type in % on Pool "Redeem" Screen

### ISSUE THREAD

**Issue by LAJazzDrum** [tendermint/liquidity#302]
When I go to redeem my pool liquidity I have to use the slider or the four percentage buttons. It would be nice if I also could type the percentage I wanted in the numeric area above the slider.

Contestant: Caterpillar1
cosmos14f729zcv5.....ggnz6l03u

I hope some of these help.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us. 

Thank you! 😊
