### ISSUE TITLE
Adding transaction history feature

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#304]
## Summary

Adding transaction history to enable tracking swaps, gas burned on transactions and so on

## Problem Definition

With current version there is no transaction history. I don't know how many transactions I made, how much tokens or USD equivalent I have burned for transactions etc. It would be nice to have this feature. 

## Proposal

Add a feature of transaction history, where can user see and track his transactions and expenses.

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Most of all, thank you for participating in our test!
Really thanks for your suggestion. But in a week, there wasn't enough time to do everything.
The next time when we run this kind of tests again, we will do our best to reflect the feedback you gave us.

Thank you! 😊
