### ISSUE TITLE
More sophisticated swaping option

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#306]
## Summary

Swap Order - create more sophisticated swaping option similar to trading

## Problem Definition

Price of cryptocurrencies is volatile. Due to this fact the amount of tokens received from swap may vary without user knowing it. 

I am actually dealing with similar issue these day on one trade I want to make while swapping for real tokens outside of the Gravity DEX. I have bought "n" amount of token A for X price hoping it will go up and then I would trade it for 200 token B. However price of  token A went down and price of token B went up. Since token B is not on the same exchange where token A, I have to swap token A to USDT, send USDT to different exchange and then buy token B. It is quite complicated and more importantly for this proposal case, the prices and ratios **vary very much**. Long story short, I don't feel like it was a smart move back then. Anyway, with that in mind it just occured to me that there might be some sort of more sophisticated swapping option to eliminate this problem in the future.

## Proposal

If the prices on the DEX are driven by "official" prices of the coins on the market, the prices will be volatile. Therefore when swapping token A to B the amount of received coins (B) might be different every time user does the swap. 

My suggestion is to implement more advanced swap "trading" window with a feature I would call "**Swap Order**".

Example of Swap Order for AKT to LUNA coin:

Swap Order:
Insert amount of AKT to swap: 100
swap if: 
AKT >= 5.5 USD/coin
LUNA <=16.8 USD/coin 
(information bar: number of received LUNA tokens: 32,738)
 Time frame - delete swap order if older than: 14 days (optional feature)
Send notification: yes/no (optional feature)

With this feature user does not have to rely on the current market prices and can use this tool for his benefit, if there is no need for him to make the swap immediately. User should be also be able to see those pending swaps in transaction history so he can manage those (for example delete the swap order).

![image](https://user-images.githubusercontent.com/83839143/117563121-14802680-b0a4-11eb-8e94-f8e449024b87.png)

![image](https://user-images.githubusercontent.com/83839143/117563132-2661c980-b0a4-11eb-8af7-583dd2c64901.png)

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
It will be very convenient feature! thank you for your suggestion👍  we will sincerely consider it.
as you know, it was a just test page : ) thanks again!
