### ISSUE TITLE
Tiny amount of coin left after "max" swap option

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#307]
## Summary of Bug
After swaping MAX amount of selected coin via "max" button, minimum amount of this token is still showing in balance.

![image](https://user-images.githubusercontent.com/83839143/117571288-3e4e4300-b0ce-11eb-8df9-4f3216b03178.png)

![image](https://user-images.githubusercontent.com/83839143/117571300-4a3a0500-b0ce-11eb-9f97-77bfb06ef529.png)

![image](https://user-images.githubusercontent.com/83839143/117571337-735a9580-b0ce-11eb-8da4-d811a50fb9c5.png)

## Version

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm

## Steps to Reproduce

When I noticed this "bug" with DVPN --> AKT and BTSG --> AKT I have decided to do it again so I can make print screens. It happened again with DVPN but BTSG seemed to swap flawlessly without any BTSG left. I did print screens and decided to do it with DVPN for the third time. However after third attempt DVPN balance was showing zero. 

Therefore I am not sure if this is a bug but I am pretty sure I have selected the "max" option every time. Maybe it will be visible to you in the action log of my wallet somehow. 

Here is how I did it:
I had selected "max" amount of the selected coin to swap into the AKT. Then after the swap I noticed that the balance is not showing zero but there is minimum amount left. I think this is not supposed to happen when you select "max" option. 

However since I was able to reproduce this two times out of three, maybe it is not a bug and it has something to do with slippage. I really don't know.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Yes, as you said it is fractional success and one of powerful feature of liquidity module
https://github.com/b-harvest/liquidity
Thank you for this level of reporting!! very impressive 👍
