### ISSUE TITLE
Different gas fees for transactions

### ISSUE THREAD

**Issue by Kopyno** [tendermint/liquidity#309]
## Summary of Bug

Different gas fees for transactions.

I set gas fees for my transactions manually. I played with gas fees a little and noticed that when you set gas to 102400 your transaction costs 0,1 ATOM instead of default 0,3 ATOM. However sometimes I get this error:

![image](https://user-images.githubusercontent.com/83839143/117578381-559d2880-b0ee-11eb-9857-f15281f35cfe.png)

What I noticed though is that the next transaction usually goes well with 102400 gas so this error seems to be quite random thing. 

## Version

I don't know how to find out the version but my contest wallet address is following:
cosmos15j58q4ujcy3ae2lgaeuk9tm9luukxy3zqqflhm

## Steps to Reproduce

This does not happen regularly, it is occasionall thing.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
As the Gravity DEX competition has ended, we are closing this issue unless it is related to either a bug or feature request to the liquidity module.
