### ISSUE TITLE
Pool Share Percentage & swap bug

### ISSUE THREAD

**Issue by pat420ch** [tendermint/liquidity#310]
## Summary of Bug

Pool share percentage displays wrong when adding nominal liquidity.

## Steps to Reproduce

add small amount (.001 etc.) of liquidity to pool. View pool share percentages... Does not reflect to balance... email for additional files ...

[Gravity DEX_ pool share percentage bug3.pdf](https://github.com/tendermint/liquidity/files/6448187/Gravity.DEX_.pool.share.percentage.bug3.pdf)
[Gravity DEX_ pool share percentage bug4.pdf](https://github.com/tendermint/liquidity/files/6448191/Gravity.DEX_.pool.share.percentage.bug4.pdf)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
[Uploading Gravity DEX_ pool share percentage bug3.pdf…]()
[Uploading Gravity DEX_ pool share percentage bug4.pdf…]()

**Comment by maydany** [comment]
Thank you for the report : ) we will improve small amount handling 😊
