### ISSUE TITLE
Can't access gravity dex from my region

### ISSUE THREAD

**Issue by roniner** [tendermint/liquidity#311]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Sorry for the inconvenience😂

**Comment by roniner** [comment]
Bug hunting my ass
Well done
