### ISSUE TITLE
App > Swap > Select a Coin > Coin Lookup Does not Support Uppercase

### ISSUE THREAD

**Issue by xhanka00** [tendermint/liquidity#313]
## Summary of Bug

When looking up token in Swap screen in "Select a Coin" pop-up window, when holding SHIFT or with CapsLock ON the look-up does not work.

## Version
Competition site as of 5/9/2021 9:38 PM UTC

## Steps to Reproduce

Swap > Select a Coin > Start typing token name wile holding SHIFT or with CapsLock ON - the input is ignored.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
it was a case sensitive issue thank you for your report! we will improve this when it comes to mainnet! : )
