### ISSUE TITLE
Dominant predator can take all benefit of arbitrage chances from other people by submitting a batch of unlimited transaction

### ISSUE THREAD

**Issue by sonntuet1997** [tendermint/liquidity#314]
## Summary of Bug

I tried batch transactions into 1 request, sent it successfully. Seems like the network supports batch transactions, which is nice because I can save gas fee!. But it’s likely that as long as the transaction has enough gas fee, someone can submit a huge amount of transactions. which can increase the time other people have to wait to have their orders processed. And the person sending batch transaction can totally calculate the best steps (transactions), and amount of coin in each step, to take all the benefit from differences from prices.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
1) Universal Swap Price : All swaps in one batch are executed with one universal swap price
tx ordering in a block doesn't matter!

please check here : )
https://github.com/b-harvest/Liquidity-Module-For-the-Hub
