### ISSUE TITLE
Action Score Error

### ISSUE THREAD

**Issue by Seranom** [tendermint/liquidity#315]
The action score listing in the gravity dex rankings tab only displays a 10 when users reach 100 points. 

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Sorry for the inconvenience 🙏, that was a display error. this one was fixed during the competition : ) it won't affect your rank at all, no worry! thank you!

**Comment by Seranom** [comment]
> Hi, thank you and congratulation for becoming the bug bounty prize winner for the Gravity DEX Competition! Please reply here with your Cosmos Hub mainnet address to receive the prize, by your github ID, until May 21, 23:59.

No worries at all, thank you for investigating this Maydany!. Below is my Cosmos mainnet address:

cosmos1zdx5xzs79tmv6vu2x3684l5q3jym8k6786tyl6

**Comment by Seranom** [comment]
Oops, I'm sorry I missed my Github.

Github ID is:
83930682

Cosmos mainnet address:
cosmos1zdx5xzs79tmv6vu2x3684l5q3jym8k6786tyl6
