### ISSUE TITLE
Slippage Tolerance issue

### ISSUE THREAD

**Issue by mudassirsyed7** [tendermint/liquidity#316]
## Summary of Bug

This one I faced when I change the Tolerance it would not stick up for long, possibly in next swap it reset back to default tolerance. Give more control over this.

## Version

Cosmos SDK Liquidity module Testnet

## Steps to Reproduce

Goto transaction settings

By default it shows 3%, instead add 3 or 4 options 0.5 1 2 and 3%

If possible add transaction deadline limit, during a case of pending 

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Thank you for report👍  in fact, that is true. for user protection purpose(forget to reset their high slippage rate to normal rate). When it comes to mainnet you can set it almost permanently : )

**Comment by mudassirsyed7** [comment]
Hi

Am I eligible for bug bounty?



62.52 ————> Total Score

279————>Rank
