### ISSUE TITLE
Unclear and misleading APY and Fee description

### ISSUE THREAD

**Issue by Ninni93** [tendermint/liquidity#321]
## Summary of Bug

 APY as annual percentage yield is clear to everybody, but that (1h) inserted in the description is kind of misleading: is it the % yield in 1 year or 1h? Same thing for fees. It makes the whole process unpractical and cumbersome.

<img width="270" alt="Schermata 2021-05-10 alle 11 02 38 AM" src="https://user-images.githubusercontent.com/83949587/117634478-3d291e80-b17f-11eb-92cd-913ad5adef41.png">

<img width="318" alt="Schermata 2021-05-10 alle 11 03 03 AM" src="https://user-images.githubusercontent.com/83949587/117634547-4c0fd100-b17f-11eb-998c-ff5aee16ca54.png">

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hallazzang** [comment]
For fees, we show the accumulated swap fee for last 1 hour. For APY, we multiply it by `24 * 365`(1 year) and then divide it by the pool's TVL.
