### ISSUE TITLE
What do you earn in pools?

### ISSUE THREAD

**Issue by Ninni93** [tendermint/liquidity#322]
## Summary of Bug

 There's a total lack of information here.. when adding liquidity to pools it must be clear what tokens are you earning by staking those couples of crypto, e.i. on FLM/NEO pool I earn FLM, on PancakeSwap I add liquidity to BNB/BTSCT to earn Cake tokens and so on. This kind of information is totally absent here, making it difficult and confusing to do a proper trade.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
It is just like uniswap pool. pool token holders earn both pair(it comes from swap fee, no yield farming). Thank you for the suggestion!👍
