### ISSUE TITLE
Keplr bug on fees

### ISSUE THREAD

**Issue by Ninni93** [tendermint/liquidity#324]
## Summary of Bug

 When changing and updating fees willing to spend for transactions, Keplr doesn't work sometimes. It makes you swap crypto with 0.1 ATOM fees but fails adding liquidity to pools with lower amount than the one selected by default.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
This issue is not about the liquidity module. You can post this issue in [Kepler](https://github.com/chainapsis/keplr-extension) repository.
