### ISSUE TITLE
Score bug

### ISSUE THREAD

**Issue by Ninni93** [tendermint/liquidity#326]
## Summary of Bug

 How is that for someone with 160.66 total score he/she has just 14 trading score?

![image](https://user-images.githubusercontent.com/83949587/117645285-b2e6b780-b18a-11eb-87e5-690d2364708e.png)

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hallazzang** [comment]
Currently there is a bug in frontend that showing `100` as `10`.
