### ISSUE TITLE
inconsistent  in exchange ratio computation in We UI can lead to unexpected behavior 

### ISSUE THREAD

**Issue by sonntuet1997** [tendermint/liquidity#328]
## Summary of Bug
![image](https://user-images.githubusercontent.com/33181397/117660590-8ef59700-b1c7-11eb-9088-675a75ea23c3.png)

![D5B93FC4-19F3-4233-8D6B-DCF14790A226](https://user-images.githubusercontent.com/33181397/117659371-117d5700-b1c6-11eb-8bfd-d86ac4bb840a.png)

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
type MsgSwapWithinBatch struct {
	SwapRequesterAddress string     // account address of the origin of this message
	PoolId               uint64     // id of the liquidity pool where this message is belong to
	SwapTypeId           uint32     // swap type id of this swap message, default 1: InstantSwap, requesting instant swap
	OfferCoin            sdk.Coin   // offer coin of this swap message
	DemandCoinDenom      string     // denom of demand coin of this swap message
	OfferCoinFee         sdk.Coin   // offer coin fee for pay fees in half offer coin
	OrderPrice           sdk.Dec    // limit order price for the order, the price is the exchange ratio of X/Y where X is the amount of the first coin and Y is the amount of the second coin when their denoms are sorted alphabetically
}

Please check order price section! : )
