### ISSUE TITLE
Action Score displaying incorrectly

### ISSUE THREAD

**Issue by smalls-glitch** [tendermint/liquidity#331]
## Summary of Bug

<same as others, incorrectly shows 10 as action score.  just want to make sure my address is on the list to be fixed.>

## Version

<my testnet address: cosmos170mqteaqkngtdfxasxpqruks4ke42w5t9yn0qv>

## Steps to Reproduce

<n/a>

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
it was a merely display error. it won't affect your rank at all. no worry! sorry for the inconvenience 🙏
