### ISSUE TITLE
Action score still incorrect  how does this affect Rankings???

### ISSUE THREAD

**Issue by Teslagrinder** [tendermint/liquidity#332]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Threre was a 100 => 10 display error. it was fixed during the competition. it was a merely display error. it won't affect your rank at all! Sorry for the inconvenience🙏
