### ISSUE TITLE
Wrong swap

### ISSUE THREAD

**Issue by AndriiVitiuk** [tendermint/liquidity#336]
## Summary of Bug
Try to swap 1000 but in fact got empty transaction

## Steps to Reproduce

Choose ->  Swap  ->  From: Run 1000   To:  NGM-> Click Swap - >

Result:
Status: Success
Paid: 0,000001 Run
Received: 0 NGM

How it possible?  and why i need this 0 value  transaction? 
Fees was paid but o got nothing

![photo_2021-05-10_22-00-13](https://user-images.githubusercontent.com/8941754/117713497-6a58e980-b1de-11eb-89f7-cfbd23cab7bb.jpg)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Thank you for the report. It is typical decimal truncation problem. We will improve this : ) thank you for reporting
