### ISSUE TITLE
Still eligible account 

### ISSUE THREAD

**Issue by BusinezBear** [tendermint/liquidity#337]
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by BusinezBear** [comment]
I have to be honest. I shouldn't be eligible for the prize anymore, however, the ranking system says I still am. I have not participated in the previous 2 day's challenges due to the previous bug I reported. I am still marked as eligible as of 3:27PM EST 5/10/21. I'm still in the top 1/3 and would feel guilty taking any prize if I didn't report it.

**Comment by simondelarue14** [comment]
You don't need to do the tasks everyday, just once was needed to be eligible

**Comment by maydany** [comment]
> I have to be honest. I shouldn't be eligible for the prize anymore, however, the ranking system says I still am. I have not participated in the previous 2 day's challenges due to the previous bug I reported. I am still marked as eligible as of 3:27PM EST 5/10/21. I'm still in the top 1/3 and would feel guilty taking any prize if I didn't report it.

One time mission complete is  Ok👌
