### ISSUE TITLE
big.int parsing error

### ISSUE THREAD

**Issue by Chjango** [tendermint/liquidity#339]
## Summary of Bug
<img width="424" alt="Screen Shot 2021-05-05 at 1 36 31 PM" src="https://user-images.githubusercontent.com/8525850/117736608-e2a6b700-b1ac-11eb-96c7-0abd08a175cc.png">

ATOM-IRIS pool TX fails when the token amount exceeds 10^9 integers, when user tries to max out the amount of tokens in their wallet

## Steps to Reproduce

1. Add liquidity to ATOM-IRIS pool
2. Max out the total amount of IRIS in your wallet using an amount that exceeds 10^8 (perhaps fewer) integers
3. Add liquidity

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by maydany** [comment]
Really thank you for the detailed report 👍
and appreciate join our test!
In later version, It will be fixed : )
