### ISSUE TITLE
Register LP token metadata to bank module

### ISSUE THREAD

**Issue by Thunnini** [tendermint/liquidity#344]
You can register the metadata of each token on the bank module.

https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-024-coin-metadata.md

It seems like the liquidity module has LP tokens for each pools. But because these LP tokens are created dynamically, they can't be registered in advance–and must be queried for the information.

I would recomnmend the LP token's metadata to be registered to the bank module.

It appears that the liquidity module's LP token denom has hashed value, and this makes it difficult to get the pool information just from the token denom without token metadata.

**Comment by dongsam** [comment]
Hi, @Thunnini Thanks for your suggestion.
We reviewed the coin-metadata registration, but it seems that similar cases, ibc token, were not registered, so we add endpoints to query pool coin through issue #345 instead.
