### ISSUE TITLE
Add and supplement events to endblock

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#347]
## Summary

Adding and supplement events to endblock to better understand results for cases that would not have been transacted swap orders

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hallazzang** [comment]
It'd be great to have such detailed information:
- `swap_transacted`
  - demand coin denom (it can be queried for now by using pool's id but having the denom in the event would benefit from reducing one extra query)
  - offered coin amount (not just exchanged amount)
  - collected swap fee from both offer coin and demand coin (it can be calculated by multiplying swap fee rate to offer/demand coin, but to not worry about the decimal errors, it'd be good to have it in the event)
