### ISSUE TITLE
DEX Circuit Breaker

### ISSUE THREAD

**Issue by dlguddus** [tendermint/liquidity#358]
### Feature Definition

- to disable all transaction types from Liquidity module

### Control

- `DEXCircuitBreaker`
    - `True` : disable all transaction types from Liquidity module
    - `False` : enable all transaction types from Liquidity module
- Authority
    - `DEXCircuitBreakerHandle` : the address which has ability to change `DEXCircuitBreaker`
    - if `null` : no address can change `DEXCircuitBreaker`
    - how to change? : via a transaction --> existing tx type or new tx type ?
      - TXCircuitBreaker : change the status of circuit breaker between `True`/`False`
- Change Via Parameter Governance
    - `DEXCircuitBreaker` and `DEXCircuitBreakerHandle` can be changed via governance
 

### Further Plan

- Generalize `Circuit Breaker` to any arbitrary list of tx types

**Comment by zmanian** [comment]
LGTM
