### ISSUE TITLE
Review the possibly outdated decimal error checks

### ISSUE THREAD

**Issue by hallazzang** [tendermint/liquidity#384]
https://github.com/tendermint/liquidity/blob/cc2cdbfe34d53c6eb1ed59f938f01e5566d1b946/x/liquidity/types/swap.go#L586-L589
This code may be outdated, needs investigation.

**Comment by hallazzang** [comment]
@dongsam It seems that there's no more `decimalErrorX` or `decimalErrorY` accumulated, is it safe to remove those logics?

**Comment by dongsam** [comment]
> @dongsam It seems that there's no more `decimalErrorX` or `decimalErrorY` accumulated, is it safe to remove those logics?

@hallazzang It looks still accumulated `decimalErrorY` for checking invariant, Let me review again the need for this variable and refactoring on https://github.com/tendermint/liquidity/issues/385

**Comment by hallazzang** [comment]
@dongsam Any update, please?

**Comment by dongsam** [comment]
> @dongsam Any update, please?

It is applied on this PR https://github.com/tendermint/liquidity/pull/410
