### ISSUE TITLE
Check correct usage of Quo()

### ISSUE THREAD

**Issue by hallazzang** [tendermint/liquidity#393]
We should check whether the denominator is zero in many places where `Quo()` is used.

**Comment by lukerhoads** [comment]
In the case that a denominator is zero, would the Quo function just return zero as well?

**Comment by lukerhoads** [comment]
Example:
`
Before: 
if orderAmt.Quo(orderPrice).TruncateInt().IsZero() {
	continue
}

After:
if types.IsDenominatorZero(orderAmt, orderPrice).Quo(orderPrice).TruncateInt().IsZero() {
	continue
}

func IsDenominatorZero(x, y sdk.Dec) sdk.Dec {
	if y.IsZero() {
		return sdk.NewDec(0)
	}
	return x
}
`

**Comment by lukerhoads** [comment]
Example:
```
Before:
if orderAmt.Quo(orderPrice).TruncateInt().IsZero() {
continue
}

After:
if types.IsDenominatorZero(orderAmt, orderPrice).Quo(orderPrice).TruncateInt().IsZero() {
continue
}

func IsDenominatorZero(x, y sdk.Dec) sdk.Dec {
if y.IsZero() {
return sdk.NewDec(0)
}
return x
}
```

**Comment by lukerhoads** [comment]
I feel like this is extreme clutter so pulling the SDK types file locally and modifying the quo function to not throw an error (and instead return 0) when big int Quo returns infinite

**Comment by hallazzang** [comment]
@lukerhoads Thank you for your suggestions!
Returning 0 when the denominator is 0 might be a viable solution, but there are some cases where returning other values makes sense.
Then we can think of another solution:
```go
func SafeQuo(a, b, c sdk.Dec) sdk.Dec {
    if b.IsZero() {
        return c
    }
    return a.Quo(b)
}
```
So this will return `c` if `b` is 0, thus `c` is acting like a default value for infinite cases.
In this way, we can choose what to be returned from the safe quotient method.
But changing every code where `Quo()` is used would be a huge work, so I'm gonna review the code and cherrypick where to patch first.

**Comment by lukerhoads** [comment]
Ahh, this is a much better solution. I appreciate the feedback, please let me know if I can help out at all.
Next time I will make sure to enable golang highlighting too haha

Thanks

**Comment by hallazzang** [comment]
Me and @dongsam checked codes that use `Quo` thoroughly and found no serious problems other than in invariant checks for now.
I think we can close this issue.
