### ISSUE TITLE
[test] Extensive simulation scenarios covering extreme edge cases

### ISSUE THREAD

**Issue by dlguddus** [tendermint/liquidity#40]
- testing decimal truncations
- message combination attack vector with swap/deposit/withdraw
- attacks with significant price distortion
- messages with very small amounts
- various limit order combinations in a batch with very edge situations
- very large number of random simulation with enoughly random messages

for milestone 2

**Comment by dlguddus** [comment]
paper review : https://web.stanford.edu/~guillean/papers/uniswap_analysis.pdf

**Comment by dlguddus** [comment]
Pool Match Only Simulation

- to verify swap result when every order is fully executed by liquidity pool
- one order per one batch
- relatively very small order amount compared to liquidity pool reserve : 0.1% of reserve
- large max slippage : 1%

Theoretical result to verify
- case1) swap X for Y
  - SwapPrice = (Reserve_X + 2*OrderAmount_X*(1-SwapFeeRate/2)) / Reserve_Y
  - SwapFeeX = OrderAmount_X*(SwapFeeRate/2)
  - SwapFeeY = SwapFeeX / SwapPrice
  - Receive_Y = (OrderAmount_X - SwapFeeX)/SwapPrice - SwapFeeY
  - Reserve_X_AfterSwap = Reserve_X + OrderAmount_X
  - Reserve_Y_AfterSwap = Reserve_Y - Receive_Y

- case2) swap Y for X
  - SwapPrice = Reserve_X / (Reserve_Y + 2*OrderAmount_Y*(1-SwapFeeRate/2))
  - SwapFeeY = OrderAmount_Y*(SwapFeeRate/2)
  - SwapFeeX = SwapFeeY * SwapPrice
  - Receive_X = (OrderAmount_Y - SwapFeeY)*SwapPrice - SwapFeeX
  - Reserve_Y_AfterSwap = Reserve_Y + OrderAmount_Y
  - Reserve_X_AfterSwap = Reserve_X - Receive_X

**Comment by dlguddus** [comment]
Other edge case tests

deposit
- deposit non-reserve tokens
- amount <= 0
- amount is very small
- deposit only one kind of token
- deposit more than 3 kinds of tokens
- not enough balance to deposit

withdraw
- request withdraw from wrong token
- request withdraw from pool tokens with amount larger than current pool token supply

pool price
- divided by zero
- too small denominator causing overflow

**Comment by dlguddus** [comment]
Actual economic model with arbitrageurs and traders

- using actual historical price of tokens (1minute price data)
- arbitrageur model 
  - arbitrageurs trade when enough profit opportunity occurs by observing historical price and pool price
  - multiple arbitrageurs competing
  - strategic order price and order amount with some randomness
- traders randomly trading tokens with random order prices and amounts
- random deposit/withdraw to/from liquidity pool

**Comment by dlguddus** [comment]
@dongsam , @defihyung lets close this issue if we think edge cases are enoughly tested from simapp.

**Comment by dongsam** [comment]
> @dongsam , @defihyung lets close this issue if we think edge cases are enoughly tested from simapp.

yes we've tested enough, but there may be some edge cases that we haven't found, so we are going to look them up more and close this issue this week.
