### ISSUE TITLE
Gaia Gravity DEX upgrade simulation from cosmoshub-4 genesis

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#403]
1. Export latest `genesis.json` from cosmoshub-4 
2. Modify `genesis.json` 
    1. validator info and power for starting test account
    2. reduce governance voting period for testing software-upgrade proposal  `sed -i '' 's/172800s/10s/' genesis.json`
3. Submit software-upgrade proposal ( need to set `--upgrade-height` )

    ```go
    gaiad tx gov submit-proposal software-upgrade Gravity-DEX -y \
      --deposit 10000000uatom \
      --title Gravity-DEX \
      --upgrade-height 0000 \
      --upgrade-info v4.3.0-testhash \
      --from validator \
      --chain-id testing \
      --description testdescription \
      --keyring-backend test
    ```

4. Vote `gaiad tx gov vote {proposal-id} yes -y --chain-id testing --from validator --keyring-backend test`
5. After panic on upgrade-height build new Gaia using [this-branch](https://github.com/b-harvest/gravity-dex/tree/add-liquidity-module-to-gaia)
6. Start with the new Gaia binary, Check and Test liquidity module functionality

- ref
    - [https://github.com/cosmos/gaia/pull/859](https://github.com/cosmos/gaia/pull/859)
    - [https://github.com/tendermint/liquidity/issues/367](https://github.com/tendermint/liquidity/issues/367)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
I'm on it :)

**Comment by dongsam** [comment]
I Added scripts and result of the upgrade test using cosmoshub-4 states 
https://github.com/b-harvest/gravity-dex-upgrade-test
