### ISSUE TITLE
Decide whether to use tendermint or cosmos for Liquidity module REST endpoints

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#404]
## Problem Definition
Currently REST endpoint path is using `/tendermint/liquidity/v1beta1/*`  [Liquidity Swagger](https://app.swaggerhub.com/apis-docs/bharvest/cosmos-sdk_liquidity_module_rest_and_g_rpc_gateway_docs/2.2.2)

But for the consistency with cosmos-sdk modules It could be `/cosmos/liquidity/v1beta1/*` [Comos Swagger](https://v1.cosmos.network/rpc/v0.41.4)

## Proposal

- [x]  Decide whether to use `tendermint` or `cosmos` for Liquidity module REST endpoints
- [x]  If it is decided to be `cosmos`, plan to proceed with the work below. ( decided to change to `cosmos` ) https://github.com/cosmos/gaia/pull/859#issuecomment-860217836
    - [x]  Change endpoints to use `cosmos` on `.proto`  https://github.com/tendermint/liquidity/pull/405
    - [x]  Update documentations

ref 
- https://github.com/cosmos/gaia/pull/859
- https://app.swaggerhub.com/apis-docs/bharvest/cosmos-sdk_liquidity_module_rest_and_g_rpc_gateway_docs/2.3.0
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Rose2161** [comment]
I apologize for being late on this.  I've been super sick..
