### ISSUE TITLE
[fix] pays fees in half offer coins, half exchanged coins

### ISSUE THREAD

**Issue by dlguddus** [tendermint/liquidity#41]
Most AMM receives fees in offer coins.
Our current implementation receives fees in exchanged coins.

But, to have most accurate post-batch pool price, the fee should be paid in half offer coins, half exchanged coins.
In this way, the post-batch pool price can be exactly same as the swap price for this batch.
This solution will prevent non-equilibrium status in orderbook after batch process because the pool price is never affected by fee payment process.

The implementation will be as below (assuming swap order from X coin to Y coin)

- when swap orders come in, store 1/2 of fees in `feeXAmtReserve` in X
- when swap orders are executed
  - `feeXAmtPaid` = `feeXAmtReserve` * `fractionalRatio` sent to liquidity pool
  - `feeYAmtPaid` = `feeXAmtPaid` / `swapPrice` sent to liquidity pool
  - note that X/Y ratio **does not change** from fee payment process
- `feeXAmtReserve` is refunded when the swap order is cancelled

Fix this in Milestone 2

**Comment by dlguddus** [comment]
This is already implemented in Milestone 1.
Below is the spec of this fix.

### 1. Reasoning

- post-swap pool price is impacted by amount of fees received from a batch process
- difference between swap price and post-swap pool price can result in non-optimal batch executions, which leave executable orders unexectued after batch
- to minimize the impact of fee payment process, it is ideal to receive fee half from offercoin, and the other half with exchangedcoin

### 2. Method

- **OfferCoin Fee Reservation ( fee before batch process, in OfferCoin )**
    - when user orders 100 Xcoin, the swap message demands
        - `OrderAmount`(in Xcoin) : 100
        - `AdvanceFeeReservation`(in Xcoin) = `OrderAmount`*(`SwapFeeRate`/2)
    - user needs to have at least 100+100**(`SwapFeeRate`/2) amount of Xcoin to successfully commit this swap message
        - the message fails when user's balance is below this amount
- **Actual Fee Payment**
    - if 10 Xcoin is executed
        - **OfferCoin Fee Payment from Reserved OfferCoin Fee**
            - `OfferCoinFeePayment`(in Xcoin) = (10/100)*`AdvanceFeeReservation`
            - `AdvanceFeeReservation` is reduced from this fee payment
        - **Back-End Fee Payment ( fee after batch process, in ExchangedCoin )**
            - `BackEndFeePayment`(in Ycoin) = `OfferCoinFeePayment` / `SwapPrice`
                - this is exactly equal value compared to advance fee payment assuming the current SwapPrice, to minimize the pool price impact from fee payment process

### 3. Frontend Issue

- user can order "**LESS**" than his/her balance because of this advance fee payment
- "**Maximum Order Amount**" can be calculated and displayed as below
    - maximum order amount : M (to be calculated)
    - user balance of Xcoin : N
    - equation : N = M + M*(`SwapFeeRate`/2)
        - M = N / (1+`SwapFeeRate`/2)
- on web interface, user cannot input more than M amount of Xcoin for swap order

**Comment by dongsam** [comment]
When the user creates swap tx, `msg.OfferCoin * params.SwapFeeRate * 0.5` for calculating `msg.OfferCoinFee` together is difficult to check whether `OfferCoinFee` is accurate due to a tiny decimal error, etc. and it may be inconvenient and difficult for users to calculate itself directly, so msg at the `NewMsgSwap` stage of the client, `OfferCoin`  Multiply `params.SwapFeeRate * 0.5` and assign to `msg.OfferCoinFee`. But the client level code cannot get params in the current state of the chain, so first of all, It defines `SwapFeeRate` as a `Const` temporarily rather than a `parameter` and automatically inserts `OfferCoinFee` into msg at the client code. If this happens, the `SwapFeeRate` cannot be adjusted from onchain through governance, but the upgrade module will be able to overcome it.

**Comment by dlguddus** [comment]
Reasoning

- frontend has difficulties to exactly calculate fee amount decided by backend.
- so we can just have minimum fee amount to receive, and let frontend decide the fee amount with enough buffer so that backend can accept the transaction when it is equal or more than what it needs.
- then, frontend has no burden to exactly calculate the minimum fee by adding very small buffer amount on it so that probability of tx acceptance is almost 100%

**Comment by dlguddus** [comment]
I agree with the change.

In version 2, we will introduce two types of liquidity pool with different SwapFeeRate. 
Therefore, we will relocate SwapFeeRate into LiquidityPoolTypes struct and we also will change LiquidityPoolTypes as Const

**Comment by dlguddus** [comment]
Implemented
