### ISSUE TITLE
gaia upgrade simulation test based hub-4 states

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#434]
To test if the liquidity module is not a problem on a Cosmos-SDK v0.43.0 based Gaia app with the latest cosmoshub-4 states test by adding a branch to https://github.com/b-harvest/gravity-dex-upgrade-test

base gaia version [v5.0.5](https://github.com/cosmos/gaia/releases/tag/v5.0.5)
new gaia version branch(temporary for test) https://github.com/b-harvest/gravity-dex/tree/upgrade-liquidity-module-based-sdk-43

**Comment by kogisin** [comment]
The following PR and docs contain the information and procedures to simulate the upgrade test.
- https://github.com/b-harvest/gravity-dex-upgrade-test/pull/4
- https://github.com/b-harvest/gravity-dex-upgrade-test/tree/kogisin/v5.0.5-upgrade-simulation/v5.0.5
