### ISSUE TITLE
[Bug] unknown query path when query or tx

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#77]
`./liquidityd tx liquidity create-liquidity-pool 1 100reservecoin1,100reservecoin2 --from node0 --home ./output/node0/liquidityd/`

when any query or tx

`Error: {"codespace":"sdk","code":6,"message":"unknown query path"}`

the unknown query path err occurred and needs to be resolved,
I spent hours but couldn't find it 

WIP in https://github.com/tendermint/liquidity/pull/76

**Comment by alessio** [comment]
Please put a `fmt.Println(path)` statement here: https://github.com/tendermint/liquidity/pull/76/files#diff-66ac8f5c2f103793df27d8b0a60a2cd4e88da365433cec1f84016558544cab3cR16

Then **rebuild** and **restart** and see what gets printed in the terminal within which the daemon is running :+1:

**Comment by dongsam** [comment]
> Please put a `fmt.Println(path)` statement here: https://github.com/tendermint/liquidity/pull/76/files#diff-66ac8f5c2f103793df27d8b0a60a2cd4e88da365433cec1f84016558544cab3cR16
> 
> Then **rebuild** and **restart** and see what gets printed in the terminal within which the daemon is running 👍

Thanks for your advice, 
Unfortunately, nothing was printed, I think this error is coming from sdk [here](https://github.com/cosmos/cosmos-sdk/blob/7ae84898de959632d5dfe165bc6cbcdbb62f867b/baseapp/abci.go%23L417) let me try print there,
It is assumed that I made a mistake in the code that sets the app, route, handler, etc.
