### ISSUE TITLE
pool identification improvement

### ISSUE THREAD

**Issue by dlguddus** [tendermint/liquidity#79]
- Current status of pool identification
  - `PoolKey` : currently we are defining `PoolKey` as `reserveCoinDenoms1-reserveCoinDenoms2-poolTypeIndex`
  - `PoolReserveAcc` : currently we are defining `PoolReserveAcc` as HASH(`PoolKey`)
  - `PoolCoinDenom` : currently we are defining `PoolCoinDenom` as STRING(`PoolReserveAcc`)

</br>

- To be
  - `PoolKey`
    - I think `PoolKey` should be defined more randomly so that it has no problem upon defining rules
    - We must assure that no `PoolKey` will not appear more than once in any circumstances
    - It is better not to use reserve coins or pool types to define `PoolKey`, but should be decided completely randomly
  - `PoolReserveAcc`
    - I think it is better to use HASH(`PoolKey` + `PoolId`) for better randomness
  - `PoolCoinDenom`
    - It is very tricky to store some informative keywords in `PoolCoinDenom`
    - But, at least, we should put information that this token is a pool token from liquidity pool of the Hub
    - Hence, `PoolCoinDenom` should look like, STRING("CosmosHubLiquidityPoolToken-"+`PoolKey`) ?

**Comment by dongsam** [comment]
The liquidity pool identification spec to be upgraded from M2 are as follows.

### Pool Identification

#### PoolKey
- `reserveCoinDenoms1/reserveCoinDenoms2/poolTypeIndex`
- string join with reserve coin denoms and `poolTypeIndex` using separator `/`
- e.g. `denomX/denomY/1`

#### PoolReserveAcc
- `sdk.AccAddress(crypto.AddressHash([]byte(PoolKey)))`
- e.g. `cosmos16ddqestwukv0jzcyfn3fdfq9h2wrs83cr4rfm3` (`D35A0CC16EE598F90B044CE296A405BA9C381E38`)

#### PoolCoinDenom
- `fmt.Sprintf("%s/%X", PoolCoinDenomPrefix, sha256.Sum256([]byte(PoolKey)))`
- PoolCoinDenomPrefix: `pool/`
- e.g. `pool/D35A0CC16EE598F90B044CE296A405BA9C381E38837599D96F2F70C2F02A23A4`
