### ISSUE TITLE
Add Tests and CI integration with 80% coverage

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#8]
- [x]  Add Github Actions for all things CI
- [x]  Add [codecov.io](https://codecov.io/) for code coverage stats
- [x]  over 80% coverag for core liquidity functions

**Comment by alessio** [comment]
I'd advise to use 1. Github Actions for all things CI 2. https://codecov.io for code coverage stats

**Comment by dongsam** [comment]
We've just reached 80 percent of coverage.
