### ISSUE TITLE
[bug] Depositing to an empty pool results in consensus failure

### ISSUE THREAD

**Issue by PaddyMc** [tendermint/liquidity#89]
### Description

After creating a pool then withdrawing all the tokens, when trying to add more tokens the chain halts

### Error

`runtime error: index out of range [0] with length 0`

#### Compiling
- `make install`

#### Initializing chain

- `liquidityd init testing --chain-id testing`
- `liquidityd keys add validator --keyring-backend test`
- `liquidityd add-genesis-account $(liquidityd keys show validator --keyring-backend test -a) 1000000000stake,1000000000token`
- `liquidityd gentx validator --chain-id testing --keyring-backend test`
- `liquidityd collect-gentxs`

- `liquidityd start > liquidityd.log 2>&1 &`

- `sleep 10`

#### Creating pool

- `liquidityd tx liquidity create-pool 1 100000000stake,100000000token --from validator --keyring-backend test --chain-id testing -y`

#### Deposit

- `liquidityd tx liquidity deposit 1 100000000stake,100000000token --from validator --keyring-backend test --chain-id testing -y
`

#### Withdraw

- `liquidityd tx liquidity withdraw 1 2000000cosmos1hdkmddemx6ttqdugxh2aqy6qjsw6lwu40pvmdv --from validator --chain-id testing --keyring-backend test -y
`

#### Deposit command that fails

- `liquidityd tx liquidity deposit 1 100000000stake,100000000token --from validator --keyring-backend test --chain-id testing -y
`

### Log

:arrow_down:  this contains the log after running the commands :arrow_down: 

[failDepositWithNoFundsInPool.log](https://github.com/tendermint/liquidity/files/5664845/failDepositWithNoFundsInPool.log)

`cat failDepositWithNoFundsInPool.log | grep CONSENSUS` to see the error without noise :+1:

**Comment by dongsam** [comment]
I fixed it in [this PR](https://github.com/tendermint/liquidity/pull/91), thank you for writing a detailed issue!

**Comment by PaddyMc** [comment]
No problem at all, happy to help

Great job fixing this issue so quickly :smile:
