### ISSUE TITLE
[bug] Trying to buy tokens from an incorrect pool results in chain halting

### ISSUE THREAD

**Issue by PaddyMc** [tendermint/liquidity#90]
### Description

When buying incorrect tokens from a pool the chain halts

### Error

- `0atom is smaller than 996atom: insufficient funds`

#### Compiling
- `make install`

#### Initializing chain

- `liquidityd init testing --chain-id testing`
- `liquidityd keys add validator --keyring-backend test`
- `liquidityd add-genesis-account $(liquidityd keys show validator --keyring-backend test -a) 1000000000stake,1000000000token`
- `liquidityd add-genesis-account $(liquidityd keys show user1 --keyring-backend test -a) 1000000000stake,1000000000atom`
- `liquidityd gentx validator --chain-id testing --keyring-backend test`
- `liquidityd collect-gentxs`

- `liquidityd start > liquidityd.log 2>&1 &`

- `sleep 10`

#### Creating pool

- `liquidityd tx liquidity create-pool 1 100000000stake,100000000token --from validator --keyring-backend test --chain-id testing -y`

#### Creating pool 2

- `liquidityd tx liquidity create-pool 1 100000000stake,100000000atom --from user1 --keyring-backend test --chain-id testing -y`

#### Swap command that fails

- `liquidityd tx liquidity swap 1 1 1 1000stake atom 1.15 --from validator --chain-id testing --keyring-backend test -y`

### Log

:arrow_down:  this contains the log after running the commands :arrow_down: 

[failBuyingWith0Balance.log](https://github.com/tendermint/liquidity/files/5664965/failBuyingWith0Balance.log)

`cat failBuyingWith0Balance.log | grep CONSENSUS` to see the error without noise :+1:

**Comment by dongsam** [comment]
I fixed it in [this PR](https://github.com/tendermint/liquidity/pull/91), thank you for writing a detailed issue! It's been a great help :)

**Comment by PaddyMc** [comment]
Ace, great job fixing this issue so quickly :smile:
