### ISSUE TITLE
optimize batch process

### ISSUE THREAD

**Issue by dlguddus** [tendermint/liquidity#96]
### timelaps for each core processes
- timelaps for each core functions and processes in batch calculation
- objective is to find the bottleneck of performance

### optimize batch calculation
- fix algorithm to make calculation as optimized as possible
- use multiprocessing to minimize calculation time under multi-core(4 or more) environment

### performance test report
- write a performance test report with analysis

**Comment by dongsam** [comment]
Performance test was conducted without multiprocessing, In 798 msgs per block scenarios, if we compare swap messages and send messages, the block time difference for Bulk/Splitted simulations are ​0.26s​ and ​0.25s respectively. We conclude that ​these differences are not significant​ considering much more computation processes existing for swap messages than send messages  

Detailed performance test results can be found [here](https://github.com/tendermint/liquidity/blob/develop/doc/Performance%2520Testing%2520for%2520Liquidity%2520Module.pdf)
